USE [master]
GO

/****** Object:  Database [BlueBinHardware]    Script Date: 10/2/2015 8:33:17 AM ******/
CREATE DATABASE [BlueBinHardware]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'BlueBinHardware', FILENAME = N'D:\RDSDBDATA\DATA\BlueBinHardware.mdf' , SIZE = 5120KB , MAXSIZE = UNLIMITED, FILEGROWTH = 10%)
 LOG ON 
( NAME = N'BlueBinHardware_log', FILENAME = N'D:\RDSDBDATA\DATA\BlueBinHardware_log.ldf' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [BlueBinHardware] SET COMPATIBILITY_LEVEL = 110
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [BlueBinHardware].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [BlueBinHardware] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [BlueBinHardware] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [BlueBinHardware] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [BlueBinHardware] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [BlueBinHardware] SET ARITHABORT OFF 
GO

ALTER DATABASE [BlueBinHardware] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [BlueBinHardware] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [BlueBinHardware] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [BlueBinHardware] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [BlueBinHardware] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [BlueBinHardware] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [BlueBinHardware] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [BlueBinHardware] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [BlueBinHardware] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [BlueBinHardware] SET  DISABLE_BROKER 
GO

ALTER DATABASE [BlueBinHardware] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [BlueBinHardware] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [BlueBinHardware] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [BlueBinHardware] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [BlueBinHardware] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [BlueBinHardware] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [BlueBinHardware] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [BlueBinHardware] SET RECOVERY FULL 
GO

ALTER DATABASE [BlueBinHardware] SET  MULTI_USER 
GO

ALTER DATABASE [BlueBinHardware] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [BlueBinHardware] SET DB_CHAINING OFF 
GO

ALTER DATABASE [BlueBinHardware] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [BlueBinHardware] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [BlueBinHardware] SET  READ_WRITE 
GO


